[tools]
chezmoi = "2.70.1"
gitleaks = "8.30.1"

[tasks.setup]
# tools.chezmoi = "2.70.0"
description = "Apply dotfiles and enter fish"
run = "chezmoi init --apply --source='{{ config_root }}'"

[tasks.secrets]
# tools.gitleaks = "8.30.1"
description = "Scan project for secrets"
run = "gitleaks dir ."

[tasks.check]
description = "Run project checks"
depends = ["secrets"]
