[settings]
color_theme = "catppuccin"
experimental = true
trusted_config_paths = ["~/Projects"]
pin = true
lockfile = true
# minimum_release_age = "7d"

[settings.npm]
package_manager = "aube"

[settings.python]
uv_venv_auto = "create|source"

[settings.github]
use_git_credentials = true

[env]
fish_greeting = ""
fish_key_bindings = "fish_vi_key_bindings"
BAT_THEME_LIGHT = "Catppuccin Latte"
BAT_THEME_DARK = "Catppuccin Mocha"
SHELL = "fish"
EDITOR = "hx"
PAGER = "bat"

[shell_alias]
sc = "scooter"
cm = "chezmoi"
lg = "lazygit"
ld = "lazydocker"
lj = "lazyjournal"
lssh = "lazyssh"
ts = "tailscale"
dc = "docker compose"

[tools]
bat = "0.26.1"
cocogitto = "7.0.0"
delta = "0.19.2"
fd = "10.4.2"
fnox = "1.24.1"
fzf = "0.72.0"
gh = "2.92.0"
gitsign = "0.16.0"
go = "1.26.3"
helix = "25.07.1"
lazydocker = "0.25.2"
lazygit = "0.61.1"
node = "26.1.0"
rg = "15.1.0"
scooter = "0.9.1"
starship = "1.25.1"
usage = "3.3.0"
uv = "0.11.14"
yazi = "26.5.6"
zoxide = "0.9.9"
python = "3.14.5"
jq = "1.8.1"
chezmoi = "2.70.3"
tlrc = "1.13.0"
atuin = "18.16.1"
eza = "0.23.4"
tmux = "3.6a"
hk = "1.45.0"
pkl = "0.31.1"
cargo-binstall = "1.19.1"
pitchfork = "2.10.0"
sd = "1.1.0"
cosign = "3.0.6"
topgrade = "17.4.0"
lazyjournal = "0.8.6"
lazyssh = "0.3.0"
pnpm = "11.1.1"
aube = "1.12.0"
viteplus = "0.1.20"
pi = "0.74.0"
