[settings]
color_theme = "catppuccin"
experimental = true
pin = true
lockfile = true
# minimum_release_age = "7d"

[settings.npm]
package_manager = "aube"

[settings.python]
uv_venv_auto = "create|source"

[settings.github]
use_git_credentials = true

[env]
fish_greeting = ""
fish_key_bindings = "fish_vi_key_bindings"
BAT_THEME_LIGHT = "Catppuccin Latte"
BAT_THEME_DARK = "Catppuccin Mocha"
SHELL = "fish"
EDITOR = "hx"
PAGER = "bat"

[shell_alias]
sc = "scooter"
cm = "chezmoi"
lg = "lazygit"
ld = "lazydocker"
lj = "lazyjournal"
ts = "tailscale"
dc = "docker compose"

[tools]
bat = "0.26.1"
cocogitto = "7.0.0"
delta = "0.19.2"
fd = "10.4.2"
fnox = "1.23.1"
fzf = "0.72.0"
gh = "2.92.0"
gitsign = "0.15.1"
go = "1.26.2"
helix = "25.07.1"
lazydocker = "0.25.2"
lazygit = "0.61.1"
node = "25.9.0"
pi = "0.72.1"
rg = "15.1.0"
scooter = "0.9.1"
starship = "1.25.1"
usage = "3.3.0"
uv = "0.11.8"
yazi = "26.1.22"
zoxide = "0.9.9"
python = "3.14.4"
jq = "1.8.1"
chezmoi = "2.70.2"
tlrc = "1.13.0"
atuin = "18.16.0"
eza = "0.23.4"
tmux = "3.6a"
hk = "1.44.3"
pkl = "0.31.1"
cargo-binstall = "1.19.0"
pitchfork = "2.9.1"
sd = "1.1.0"
cosign = "3.0.6"
"github:pnpm/pnpm" = "11.0.4"
topgrade = "17.4.0"
lazyjournal = "0.8.6"
lazyssh = "0.3.0"
