[settings]
color_theme = "catppuccin"
experimental = true
trusted_config_paths = ["~/Projects"]
pin = true
lockfile = true
# minimum_release_age = "7d"
env_shell_expand = true

[settings.npm]
package_manager = "aube"

[settings.python]
uv_venv_auto = "create|source"

[settings.github]
use_git_credentials = true

[env]
fish_greeting = ""
fish_key_bindings = "fish_vi_key_bindings"
BAT_THEME_LIGHT = "Catppuccin Latte"
BAT_THEME_DARK = "Catppuccin Mocha"
SHELL = "fish"
EDITOR = "hx"
PAGER = "bat"
XDG_CONFIG_HOME = "$HOME/.config"
XDG_CACHE_HOME = "$HOME/.cache"
XDG_DATA_HOME = "$HOME/.local/share"
XDG_STATE_HOME = "$HOME/.local/state"
GNUPGHOME="$XDG_DATA_HOME/gnupg"
TUF_ROOT="$XDG_DATA_HOME/sigstore/root"
STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship.toml"
STARSHIP_CACHE="$XDG_CACHE_HOME/starship"
RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/config"
ANSIBLE_HOME="${XDG_CONFIG_HOME}/ansible"
ANSIBLE_CONFIG="${XDG_CONFIG_HOME}/ansible.cfg"
ANSIBLE_GALAXY_CACHE_DIR="${XDG_CACHE_HOME}/ansible/galaxy_cache"
ANSIBLE_LOCAL_TEMP="${XDG_CACHE_HOME}/ansible/tmp"
ANSIBLE_SSH_CONTROL_PATH_DIR="${XDG_CACHE_HOME}/ansible/cp"
ANSIBLE_ASYNC_DIR="${XDG_CACHE_HOME}/ansible_async"
AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME/aws/credentials"
AWS_CONFIG_FILE="$XDG_CONFIG_HOME/aws/config"
RUFF_CACHE_DIR="$XDG_CACHE_HOME/ruff"
NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
NUGET_PACKAGES="$XDG_CACHE_HOME/NuGetPackages"
DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
KUBECONFIG="$XDG_CONFIG_HOME/kube"
KUBECACHEDIR="$XDG_CACHE_HOME/kube"
PYTHON_HISTORY="$XDG_STATE_HOME/python_history"
PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python"
PYTHONUSERBASE="$XDG_DATA_HOME/python"
GOPATH="$XDG_DATA_HOME/go"
GOMODCACHE="$XDG_CACHE_HOME/go/mod"
GOCACHE="$XDG_CACHE_HOME/go-build"
RUSTUP_HOME="$XDG_DATA_HOME/rustup"
CARGO_HOME="$XDG_DATA_HOME/cargo"
BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundle"
BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundle/config"
BUNDLE_USER_PLUGIN="$XDG_DATA_HOME/bundle"
PHP_HISTFILE="$XDG_STATE_HOME/php/history"
SQLITE_HISTORY="$XDG_STATE_HOME/sqlite_history"
CODEX_HOME="$XDG_CONFIG_HOME/codex"
PI_CODING_AGENT_DIR="${XDG_CONFIG_HOME}/pi"

[shell_alias]
sc = "scooter"
cm = "chezmoi"
lg = "lazygit"
ld = "lazydocker"
lj = "lazyjournal"
ts = "tailscale"
dc = "docker compose"

[tools]
bat = "0.26.1"
cocogitto = "7.0.0"
delta = "0.19.2"
fd = "10.4.2"
fnox = "1.24.1"
fzf = "0.72.0"
gh = "2.92.0"
gitsign = "0.16.0"
go = "1.26.3"
helix = "25.07.1"
lazydocker = "0.25.2"
lazygit = "0.61.1"
node = "26.1.0"
rg = "15.1.0"
scooter = "0.9.1"
starship = "1.25.1"
usage = "3.3.0"
uv = "0.11.14"
yazi = "26.5.6"
zoxide = "0.9.9"
python = "3.14.5"
jq = "1.8.1"
chezmoi = "2.70.3"
tlrc = "1.13.0"
atuin = "18.16.1"
eza = "0.23.4"
tmux = "3.6a"
hk = "1.45.0"
pkl = "0.31.1"
cargo-binstall = "1.19.1"
pitchfork = "2.10.0"
sd = "1.1.0"
cosign = "3.0.6"
topgrade = "17.4.0"
lazyjournal = "0.8.6"
pnpm = "11.1.1"
aube = "1.13.1"
viteplus = "0.1.21"
pi = "0.74.0"
bun = "1.3.14"
