[settings]
lockfile = true

[env]
SHELL="fish"

[tools]
usage = "latest"
chezmoi = "latest"
zoxide = "latest"
fzf = "latest"
fd = "latest"
rg = "latest"
bat = "latest"
pi = "latest"
lazygit = "latest"
uv = "latest"
pnpm = "latest"
go = "latest"
"aqua:lxc/incus" = "latest"
